#file to configure Travis
language: python
python:
    - "2.7"
#install dependencies
install:
    - pip install fuzzywuzzy
#run some of the files
script: python parser.py
        python processData.py
        python spellcheck.py
branches:
    only:
        - master
